### ISSUE TITLE
Groovy 2.5

### ISSUE THREAD

**Issue by aaloise** [vert-x3/vertx-lang-groovy#57]
Apache Groovy 2.5 was recently released.

Consider to upgrade at the appropriate time.

Groovy 2.5 requires JDK8+ to build and JDK7 is the minimum version of the JRE that it supports.

**Comment by vietj** [comment]
I think one issue is that the groovy-all jar does not exist anymore

**Comment by vietj** [comment]
so we need to find the right dep to use

**Comment by aaloise** [comment]
Found the following post on Twitter:

@daniel_sun
Since #groovylang 2.5.0, pls grab groovy-all dependency as follows:
#gradle:
compile 'org.codehaus.groovy:groovy-all:x.y.z'

#maven:
<groupId>org.codehaus.groovy</groupId>
<artifactId>groovy-all</artifactId>
<version>x.y.z</version>
<type>pom</type> 

https://twitter.com/daniel_sun/status/1003474637697642496

**Comment by vietj** [comment]
can you make a PR for this project ?

**Comment by aaloise** [comment]
Done https://github.com/vert-x3/vertx-lang-groovy/issues/58

**Comment by aaloise** [comment]
And also #59 , in #58 I forgot to edit pom.xml of codegen

**Comment by vietj** [comment]
can you close them and make a single PR @aaloise ?

**Comment by aaloise** [comment]
Closed #58 and #59, also created #60 with both files changed

**Comment by aaloise** [comment]
Well, since #60 didn't work, I look around a little and found this at Grovvy install directions using Maven in the official site:

```xml
<groupId>org.codehaus.groovy</groupId>
<artifactId>groovy-all</artifactId>
<version>2.5.0</version>
```

http://groovy-lang.org/install.html#_maven_repository

Seems pretty much the same like it was with 2.4

**Comment by aaloise** [comment]
@vietj sorry to ask, but witch version of JDK was used to compile after #60 got merged?

**Comment by vietj** [comment]
java version "1.8.0_172"

**Comment by aaloise** [comment]
Is it ok if I make a PR with the instructions in Groovy site? Looks the same way that used to work with 2.4, but who knows? Might work.

**Comment by aaloise** [comment]
The compilation errors are because at compile time packages from Groovy aren't being found. Errors such as "package org.codehaus.groovy.ast does not exist" and "ScriptVerticle.java:[38,17] cannot find symbol  symbol:   class Script  location: class io.vertx.lang.groovy.ScriptVerticle" are happening.

It's like Groovy dependency does not get downloaded or it is not present in compile phase. I don't know exactly what it is, but I suspect that something must be ajusted in pom.xml, but don't know what precisely.

Don't know much about Maven, so I got stuck on this one.
